# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  bpapi:
    image: bpapi
    build:
      context: ../
      dockerfile: ./bpapi/Dockerfile
    ports:
      - 5117:5117
    environment:
      - ASPNETCORE_ENVIRONMENT=Development    
      - ASPNETCORE_URLS=http://+:5117
  bmiapi:
    image: bmiapi
    build:
      context: ../
      dockerfile: ./bmiapi/Dockerfile
    ports:
      - 5116:5116
    environment:
      - ASPNETCORE_ENVIRONMENT=Development    
      - ASPNETCORE_URLS=http://+:5116      