# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  db:
    image: sqlserver
    build:
      context: ./sql
      dockerfile: Dockerfile
    environment:
        SA_PASSWORD: "Yukon900"
        ACCEPT_EULA: "Y"
    ports:
      - 1433:1433 
      
  bpapi:
    image: bpapi
    build:
      context: ../
      dockerfile: ./bpapi/Dockerfile
    deploy:
      mode: replicated
      replicas: 2      
 #   ports:
 #     - 5117:5117
    environment:
      - ASPNETCORE_ENVIRONMENT=Development    
      - ASPNETCORE_URLS=http://+:5117

  bmiapi:
    image: bmiapi
    build:
      context: ../
      dockerfile: ./bmiapi/Dockerfile
    deploy:
      mode: replicated
      replicas: 2      
#    ports:
#      - 5116:5116
    environment:
      - ASPNETCORE_ENVIRONMENT=Development    
      - ASPNETCORE_URLS=http://+:5116      

  dhccmdhandler:
    image: dhccmdhandler
    build:
      context: ../
      dockerfile: ./dhccmdhandler/Dockerfile
    deploy:
      mode: replicated
      replicas: 2      
    environment:
      - ASPNETCORE_ENVIRONMENT=Development    
      - DOTNET_ENVIRONMENT=Development      
      - Logging__LogLevel__dhc=Trace
      - Logging__LogLevel__dhccmdhandler=Trace
      - RabbitMq__RabbitHost=rabbitmq
      - RabbitMq__RabbitUserName=guest
      - RabbitMq__RabbitPassword=guest
      - RabbitMq__RabbitPort=5672
      - OrleansConnection__Host=dhcsilo
    depends_on:
      - dhcsilo
      - db

  dhcsilo:
    image: dhcsilo
    build:
      context: ../
      dockerfile: ./Silo/Dockerfile    
    restart: on-failure:20
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
      - BmiWebApiSettings__BaseUrl=http://bmiapi:5116/
      - BpWebApiSettings__BaseUrl=http://bpapi:5117/      
      - EventStoreClient__ConnectionString=esdb://admin:changeit@eventstore:2113?tls=false
      - PostCodeApi__BaseUrl=https://api.postcodes.io/postcodes/
      - PostCodeApi__SlidingCacheLength=00:10:00
      - PostCodeApi__AbsoluteCacheLength=01:00:00
      - Logging__LogLevel__dhc=Trace
      - Logging__LogLevel__Silo=Trace
      - OrleansConnection__DbHost=db
    depends_on:
      - rabbitmq
      - eventstore
      - bmiapi
      - bpapi

  dhcapi:
    image: dhcapi
    restart: on-failure:20
    build:
      context: ../
      dockerfile: ./dhcapi/Dockerfile
    deploy:
      mode: replicated
      replicas: 1      
    ports:
      - 5118:5118      
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5118
      - EventStoreClient__ConnectionString=esdb://admin:changeit@eventstore:2113?tls=false
      - RabbitMq__RabbitHost=rabbitmq
      - RabbitMq__RabbitUserName=guest
      - RabbitMq__RabbitPassword=guest
      - RabbitMq__RabbitPort=5672

    depends_on:
      - rabbitmq
      - eventstore
      - bmiapi
      - bpapi
      - dhcsilo

  rabbitmq:
    image: rabbitmq-custom
    build:
      context: .
      dockerfile: ./rabbitmq/Dockerfile    
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/rabbitmq/lib/
        - ~/.docker-conf/rabbitmq/log/:/var/rabbitmq/log/
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  eventstore:
      image: eventstore/eventstore:20.10.2-buster-slim
      environment:
        - EVENTSTORE_CLUSTER_SIZE=1
        - EVENTSTORE_RUN_PROJECTIONS=All
        - EVENTSTORE_START_STANDARD_PROJECTIONS=true
        - EVENTSTORE_EXT_TCP_PORT=1113
        - EVENTSTORE_HTTP_PORT=2113
        - EVENTSTORE_INSECURE=true
        - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
        - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      ports:
        - "1113:1113"
        - "2113:2113"
      volumes:
        - ~/.docker-conf/eventstore/data:/var/lib/eventstore
        - ~/.docker-conf/eventstore/logs:/var/log/eventstore     
      healthcheck:
        test:
          [
              'CMD-SHELL',
              'curl --fail --insecure https://eventstore:2113/health/live || exit 1',
          ]
        interval: 30s
        timeout: 30s
        retries: 3          