# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  bpapi:
    image: bpapi
    build:
      context: ../
      dockerfile: ./bpapi/Dockerfile
    ports:
      - 5117:5117
    environment:
      - ASPNETCORE_ENVIRONMENT=Development    
      - ASPNETCORE_URLS=http://+:5117
  bmiapi:
    image: bmiapi
    build:
      context: ../
      dockerfile: ./bmiapi/Dockerfile
    ports:
      - 5116:5116
    environment:
      - ASPNETCORE_ENVIRONMENT=Development    
      - ASPNETCORE_URLS=http://+:5116      


  
  dhcsilo:
    image: dhcsilo
    build:
      context: ../
      dockerfile: ./Silo/Dockerfile    
    restart: on-failure:20
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
      - BpWebApiSettings__BaseUrl=http://bmiapi:5116/
      - EventStoreClient__ConnectionString=esdb://admin:changeit@eventstore:2113?tls=false
      - RabbitMq__RabbitHost=rabbitmq
      - RabbitMq__RabbitUserName=guest
      - RabbitMq__RabbitPassword=guest
      - RabbitMq__RabbitPort=5672
      - PostCodeApi__BaseUrl=https://api.postcodes.io/postcodes/
      - PostCodeApi__SlidingCacheLength=00:10:00
      - PostCodeApi__AbsoluteCacheLength=01:00:00
      - Logging__LogLevel__dhc=Trace
      - Logging__LogLevel__Silo=Trace

    depends_on:
      - rabbitmq
      - eventstore
      - bmiapi
      - bpapi

  dhcapi:
    image: dhcapi
    restart: on-failure:20
    build:
      context: ../
      dockerfile: ./dhcapi/Dockerfile
    ports:
      - 5118:5118
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5118
      - BpWebApiSettings__BaseUrl=http://bmiapi:5116/
      - EventStoreClient__ConnectionString=esdb://admin:changeit@eventstore:2113?tls=false
      - RabbitMq__RabbitHost=rabbitmq
      - RabbitMq__RabbitUserName=guest
      - RabbitMq__RabbitPassword=guest
      - RabbitMq__RabbitPort=5672
      - PostCodeApi__BaseUrl=https://api.postcodes.io/postcodes/
      - PostCodeApi__SlidingCacheLength=00:10:00
      - PostCodeApi__AbsoluteCacheLength=01:00:00
      - OrleansConnection__Host=dhcsilo
    depends_on:
      - rabbitmq
      - eventstore
      - bmiapi
      - bpapi
      - dhcsilo

  rabbitmq:
    image: rabbitmq-custom
    build:
      context: .
      dockerfile: ./rabbitmq/Dockerfile    
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/rabbitmq/lib/
        - ~/.docker-conf/rabbitmq/log/:/var/rabbitmq/log/
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  eventstore:
      image: eventstore/eventstore:20.10.2-buster-slim
      environment:
        - EVENTSTORE_CLUSTER_SIZE=1
        - EVENTSTORE_RUN_PROJECTIONS=All
        - EVENTSTORE_START_STANDARD_PROJECTIONS=true
        - EVENTSTORE_EXT_TCP_PORT=1113
        - EVENTSTORE_HTTP_PORT=2113
        - EVENTSTORE_INSECURE=true
        - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
        - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      ports:
        - "1113:1113"
        - "2113:2113"
      volumes:
        - type: volume
          source: eventstore-volume-data
          target: /var/lib/eventstore
        - type: volume
          source: eventstore-volume-logs
          target: /var/log/eventstore        
      healthcheck:
        test:
          [
              'CMD-SHELL',
              'curl --fail --insecure https://eventstore:2113/health/live || exit 1',
          ]
        interval: 30s
        timeout: 30s
        retries: 3          
volumes:
  eventstore-volume-data:
  eventstore-volume-logs:          